export class CodegripMessages {
    /* Error Messages */
    public static RepositoryList_Not_Found = "Unable to find repositories. Please check if your connected source control has repositories added under it."
    public static Select_Source_Control = "Please select a source control."
    public static Invalid_GitURL = "Please enter a valid Git URL."
    public static Project_Review = "Please wait, we are reviewing your project."
    public static Something_Went_Wrong = "Something went wrong, please try again."
    public static Invalid_Image_Type = "Image type should be JPEG or PNG."
    public static File_Not_Found = "Unable to find content in the selected file."
    public static Branch_Quality_Not_Found = "No analytics found on selected branch."
    public static Select_Atleast_One_Source = "Please connect atleast one source control account."
    public static No_Branch_To_Change = "You don't have more branches to change."
}

export class CodegripConstantValue {
    public static currentPlanUsersLimit = 1000;
    public static Stripe_Logo_URL = "https://s3-us-west-2.amazonaws.com/dev-codegrip-images/Default+profile+images/CG_logo_stripe.png"
}

export class EventTitles {
    public static Github_Login = "login_with_github"
    public static Bitbucket_Login = "login_with_bitbucket"
    public static Google_Login = "login_with_google"
    public static Project_Search = "projects_searchbox"
    public static Add_Repository = "projects_add_repositories_button"
    public static Manage_Users = "projects_more_manage_users"
    public static Change_Branch = "projects_more_change_branch"
    public static Delete_Project = "projects_more_delete_project"
    public static Project_Change_Branch = "projects_change_branch"
    public static Progress_New_Issues = "projects_progress_new_issues"
    public static Progress_Security = "projects_progress_security"
    public static Progress_Activity_ViewOnGithub = "projects_progress_activitylog_viewongithub"
    public static Issue_Filters = "projects_issues_filters"
    public static Issue_Filters_Bugs = "projects_issues_filters_type_bug"
    public static Issue_Filters_Codesmells = "projects_issues_filters_type_codesmell"
    public static Issue_Filters_Vulnerability = "projects_issues_filters_type_vulnerability"
    public static Issue_Filters_Blocker = "projects_issues_filters_severity_blocker"
    public static Issue_Filters_Critical = "projects_issues_filters_severity_critical"
    public static Issue_Filters_Info = "projects_issues_filters_severity_info"
    public static Issue_Filters_Major = "projects_issues_filters_major"
    public static Issue_Filters_Minor = "projects_issues_filters_minor"
    public static Issue_Filters_Date = "projects_issues_filters_date"
    public static Issue_File_Open = "projects_issues_open_file"
    public static Issue_Solution_Arrow_Down = "projects_issues_downarrow_suggested solution"
    public static Issue_Solution_Arrow_Up = "projects_issues_uparrow_suggested solution"
    public static Issue_Solution_Close = "projects_issues_closebutton_suggested solution"
    public static Codefile_Solution_Arrow_Down = "projects_issues_codefile_downarrow_suggested solution"
    public static Codefile_Solution_Arrow_Up = "projects_issues_codefile_uparrow_suggested solution"
    public static Codefile_Solution_Close = "projects_issues_codefile_closebutton_suggested solution"
    public static Security_Category_Select = "projects_security_category_select"
    public static Security_Hotspot_Click = "projects_security_hotspots_click"
    public static Code_Search = "projects_code_searchbox"
    public static Code_Sub_Folder = "projects_code_select_subfolder"
    public static Code_Select_File = "projects_code_select_file"
    public static Code_Sub_Folder_Search = "projects_code_subfolder_searchbox"
    public static Project_Dashboard_Share_Button = "projects_dashboard_share_analytics_buttonclick"
    public static Project_Dashboard_Shared_Actual = "projects_dashboard_share_analytics_actualshare_from_modal"
    public static Plans_Startup = "payment_plans_startup"
    public static Plans_Business = "payment_plans_business"
    public static Plans_Enterprise = "payment_plans_enterprise"
    public static Plans_Custom = "payment_plans_custom"
    public static Plans_Upgrade = "upgrade_plan_click"
}